# Várias opções de config no link [https://github.com/invertase/melos/issues/142]

name: gallery

packages:
  - packages/*


scripts:
  watch:
    run: dart run build_runner watch --delete-conflicting-outputs

  build:
    run: dart run build_runner build --delete-conflicting-outputs
