name: gallery
description: iPets
publish_to: none
version: 1.2.0+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^9.0.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  flutter_bloc:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: any
  go_router: ^12.1.1
  http: ^1.1.0
  package_info_plus: ^4.2.0
  skeletonizer: ^0.8.0
  url_launcher: ^6.2.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0

dev_dependencies:
  bloc_test: ^9.1.6

  build_runner: ^2.4.7
  build_test: ^2.0.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  melos: ^3.2.0
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/anims/
  # - assets/ca/
