name: gallery
description: A new Flutter project.
publish_to: none
version: 1.0.2+8
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: any
  go_router: ^12.1.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.2.0
  skeletonizer: ^0.8.0
  url_launcher: ^6.2.1
dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.0.0
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  melos: ^3.2.0
  mockito: ^5.4.3
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  # - assets/ca/
